swagger: '2.0'
info:
  version: '1.0.0'
  title: EduPlatform.API
host: localhost:3000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /group/{groupId}:
    get:
      summary: Get a single group
      parameters:
        - in: path
          name: groupId
          required: true
          type: string
      responses:
        '200':
          description: Ok
  /group:
    get:
      summary: Get all the groups
      responses:
        '200':
          description: Object with all groups.
  /group/createGroup:
    post:
      summary: Create a group
      parameters:
        - in: body
          name: mentor
          required: true
          type: string
      responses:
        '200':
          description: Group created
    