swagger: '2.0'
info:
  version: '1.0.0'
  title: EduPlatform.API
host: localhost:3000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /group:
    get:
      summary: Get all the groups
      responses:
        '200':
          description: Object with all groups.
          schema:
            type: object
            properties:
              numberOfGroups:
                type: integer
                example: 1
              result:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    groupName:
                      type: string
                    mentor:
                      type: string
                    members:
                      type: array
                      items:
                        type: object
                        properties:
                          _id: 
                            type: string
        '500':
          description: Internal server error
  /group/{groupId}:
    get:
      summary: Get a single group
      parameters:
        - in: path
          name: groupId
          required: true
          type: string
      responses:
        '200':
          description: Object with a single group
          schema:
            type: object
            properties:
             group:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    groupName:
                      type: string
                    mentor:
                      type: string
                    members:
                      type: array
                      items:
                        type: object
                        properties:
                          _id: 
                            type: string
        '500':
          description: Internal server error
  /group/createGroup:
    post:
      summary: Create a group
      parameters:
        - name: groupBody
          in: body
          description: Object with mentor's _id and groupName
          schema:
            type: object
            required: 
              - mentor
              - groupName
            properties:
              mentor:
                type: string
              groupName:
                type: string
      responses:
        '201':
          description: Group created
          schema:
            type: object
            properties:
              message:
                type: string
                example: Group created
        '404':
          description: This group name is already taken
          schema:
            type: object
            properties:
              message:
                type: string
                example: This group name is already taken
        '500':
          description: Internal server error
  /group/addMember/{groupId}:
    put:
      summary: Add a member to the group
      parameters:
        - name: groupId
          in: path
          type: string
          required: true
        - name: userBody
          in: body
          required: true
          schema:
            type: object
            required:
              - email
            properties:
              email:
                type: string
      responses:
        '200':
          description: User added
  /group/deleteMember/{groupId}:
    put:
      summary: Delete a member from the group
      parameters:
        - name: groupId
          in: path
          type: string
          required: true
        - name: userBody
          in: body
          required: true
          schema:
            type: object
            required:
              - _id
            properties:
              _id:
                type: string
      responses:
        '200':
          description: User deleted from the group
  /group/changeName/{groupId}:
    put:
      summary: Change a group name
      parameters:
        - name: groupId
          in: path
          required: true
          type: string
        - name: nameBody
          in: body
          required: true
          schema:
            type: object
            required:
              - newName
            properties:
              newName:
                type: string
      responses:
        '200':
          description: Ok
          schema:
            type: object
            properties:
              message:
                type: string